dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${spring.cloud.nacos.config.server-addr}
  consumer:
    check: false
spring:
  cloud:
    sentinel:
      enabled: false