server:
  port: 9008
spring:
  application:
    name: yeju-payment-rest-api

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

