dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
  provider:
    port: 20881
spring:
  cloud:
    nacos:
      server-addr: 8.129.77.225:8848
      discovery:
        namespace: ed63a92c-9b8c-4169-9a60-bc19059ae061
        log-name: ../pers.lbf.yeju.common.log/nacos.pers.lbf.yeju.common.log
      config:
        namespace: b6649ae6-6781-4a30-94a0-132f823a00eb
    sentinel:
      enabled: false
      log:
        dir: ../pers.lbf.yeju.common.log
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: hewenping
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 1
#    timeout: 3000
#    database: 1