server:
  port: 81
spring:
  cloud:
    nacos:
      server-addr: 8.129.77.225:8848
      discovery:
#        yeju
        namespace: ed63a92c-9b8c-4169-9a60-bc19059ae061
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authserver
          uri: lb://authserver
          predicates:
            - Path=/authserver/**

dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
    check: false
  consumer:
    check: false
  application:
    name: ${spring.application.name}
  config-center:
    namespace: yeju-dubbob6649ae6-6781-4a30-94a0-132f823a00eb

