server:
  port: 81
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: authserver
#          uri: lb://authserver
#          predicates:
#            - Path=/authserver/**

dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    check: false
  consumer:
    check: false
  application:
    name: ${spring.application.name}

