spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      business:
        jdbc-url: jdbc:mysql://192.168.0.123:3306/yeju_core?userSSL=false&serverTimezone=GMT%2B8
        username: yeju
        password: yeju@20200306
      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 3000
      validation-query: SELECT now()
      filter:
        wall:
          enabled: true
          db-type: mysql

