spring:
  application:
    name: yeju-provider
  elasticsearch:
    rest:
      uris: http://192.168.1.101:9200
  #      username: elastic
  #      password: admin@2020
  data:
    elasticsearch:
      client:
        reactive:
          #          password: admin@2020
          #          use-ssl: true
          #          username: elastic
          endpoints: 192.168.1.101:9200

dubbo:
  application:
    name: ${spring.application.name}
  #采用协议方式和端口号
  protocol:
    name: dubbo
    port: 20882
    host: 192.168.1.110


logging:
  level:
    pers.lbf.yeju.provider.message.notice.dao: debug
    pers.lbf.yeju.provider.customer.dao: debug
    pers.lbf.yeju.provider.basedata.community.dao: debug

