dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${spring.cloud.nacos.config.server-addr}
    check: false
spring:
  cloud:
    nacos:
      server-addr: 8.129.77.225:8848
      discovery:
        namespace: ed63a92c-9b8c-4169-9a60-bc19059ae061
    sentinel:
      enabled: false
      log:
        dir: ./logs


