server:
  port: 9007

spring:
  application:
    name: yeju-trade-rest-api



#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus

