server:
  port: 9010
spring:
  application:
    name: yeju-all-rest-api

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus

