server:
  port: 9003
spring:
  application:
    name: yeju-message

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus
