dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
  consumer:
    check: false
  config-center:
    namespace: yeju-dubbob6649ae6-6781-4a30-94a0-132f823a00eb
  provider:
    port: 20885
spring:
  cloud:
    sentinel:
      enabled: false
    nacos:
      server-addr: 8.129.77.225:8848
      discovery:
        namespace: ed63a92c-9b8c-4169-9a60-bc19059ae061
      config:
        namespace: b6649ae6-6781-4a30-94a0-132f823a00eb
