server:
  port: 9005
spring:
  application:
    name: yeju-product-web

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus

